### ISSUE TITLE
Incorrect directory used on Mac

### ISSUE THREAD

**Issue by adamrodger** [adamrodger/gctx#1]
On a Mac, `gcloud` stores config in `~/.config/gcloud` just like on Linux. However, `gctx` uses the Apple developer guidelines to look in `~/Library/Application Support/gcloud`, which obviously doesn't work.

There will need to be a platform-specific override for forcing Mac to use the proper location.

**Comment by c3st7n** [comment]
I have a patch for this, but also, gcloud honours the `CLOUDSDK_CONFIG` env var so we should probably add something to use that if it set too.

**Comment by adamrodger** [comment]
Fixed in #6

**Comment by adamrodger** [comment]
Yeah we should def honour that env var as well. That would enable some integration tests in a temp for as well

**Comment by adamrodger** [comment]
Raised #7 to support CLOUDSDK_CONFIG
